# Generated by Django 5.2 on 2025-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusitem',
            options={'ordering': ['week_starting']},
        ),
        migrations.RemoveField(
            model_name='focusitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='focusitem',
            name='week_starting',
            field=models.DateTimeField(default='2025-05-01T00:00:00Z'),
            preserve_default=False,
        ),
    ]
