# Generated by Django 5.2 on 2025-05-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_alter_focusitem_options_remove_focusitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='focusitem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
