# Generated by Django 5.2 on 2025-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_focusitem_icon_alter_focusitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusitem',
            name='description',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='focusitem',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
