# Generated by Django 5.2 on 2025-08-15 17:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]