# Generated by Django 5.2 on 2025-08-15 17:49
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20250815_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='rating',
        ),
    ]
