# Generated by Django 5.2 on 2025-08-15 17:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_quote_rating'),
    ]

    operations = [
    ]