# Generated by Django 5.2 on 2025-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_movie_user_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
