# Generated by Django 5.2 on 2025-08-15 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_movie_year_alter_series_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olid', models.CharField(max_length=20, unique=True)),
                ('work_key', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True)),
                ('publish_date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_small', models.URLField(blank=True, null=True)),
                ('cover_medium', models.URLField(blank=True, null=True)),
                ('cover_large', models.URLField(blank=True, null=True)),
                ('identifiers', models.JSONField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('olid',), name='unique_book_olid')],
            },
        ),
    ]
