# Generated by Django 5.2 on 2025-08-15 23:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_book_olid',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover_large',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='edition_key',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pages',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_medium',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_small',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='olid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('olid',), name='unique_olid'),
        ),
    ]
