# Generated by Django 5.2 on 2025-08-16 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_book_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_olid',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='olid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_title'),
        ),
    ]
