# Generated by Django 5.2 on 2026-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_remove_book_unique_title_book_unique_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='my_completed',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='my_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='my_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='my_completed',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='my_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='my_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
