# Generated by Django 5.2 on 2026-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_movie_my_completed_movie_my_notes_movie_my_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='my_completed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='my_completed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
