# Generated by Django 5.2 on 2026-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_alter_movie_my_completed_alter_series_my_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='my_completed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='my_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='my_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
