# Generated by Django 5.2 on 2025-04-27 11:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitperiodentry',
            name='habit',
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habits.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='HabitPeriod',
        ),
        migrations.DeleteModel(
            name='HabitPeriodEntry',
        ),
    ]
