# Generated by Django 5.2 on 2025-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habitperiodentry_habit_habitrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color_scheme',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
