# Generated by Django 5.2 on 2025-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_color_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='enabled_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01T00:00:00'),
            preserve_default=False,
        ),
    ]
