# Generated by Django 5.2 on 2025-11-16 14:50

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_updated_at_habit_disabled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='disabled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='enabled_at',
            field=models.DateField(default=django.db.models.functions.datetime.Now),
        ),
    ]
