# Generated by Django 5.2 on 2025-11-16 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_created_at_alter_habit_disabled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='enabled_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
