# Generated by Django 5.2 on 2025-11-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('tasks', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spaces.space'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
