# Generated by Django 5.2 on 2025-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_resource_links_task_space_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
