# Generated by Django 5.2 on 2026-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
