# Generated by Django 5.2 on 2026-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_activity_duration_alter_activity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default='20'),
            preserve_default=False,
        ),
    ]
