# Generated by Django 5.2 on 2025-10-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='reflections',
            new_name='reflection',
        ),
    ]
