# Generated by Django 5.2 on 2025-10-19 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_rename_reflections_checkin_reflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='energy_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='focus_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mood',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='stress_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
