# Generated by Django 5.2 on 2025-10-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_alter_checkin_energy_level_alter_checkin_focus_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(),
        ),
    ]
