# Generated by Django 5.2 on 2025-08-11 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('imdb_id',), name='unique_imdb_id')],
            },
        ),
    ]
